#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationManager.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="educationalManager")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertcourse(course instance);
    partial void Updatecourse(course instance);
    partial void Deletecourse(course instance);
    partial void Insertdepartment(department instance);
    partial void Updatedepartment(department instance);
    partial void Deletedepartment(department instance);
    partial void Insertgrade(grade instance);
    partial void Updategrade(grade instance);
    partial void Deletegrade(grade instance);
    partial void Insertsemester(semester instance);
    partial void Updatesemester(semester instance);
    partial void Deletesemester(semester instance);
    partial void Insertteacher(teacher instance);
    partial void Updateteacher(teacher instance);
    partial void Deleteteacher(teacher instance);
    partial void InsertwebInfo(webInfo instance);
    partial void UpdatewebInfo(webInfo instance);
    partial void DeletewebInfo(webInfo instance);
    partial void InsertmenuInfo(menuInfo instance);
    partial void UpdatemenuInfo(menuInfo instance);
    partial void DeletemenuInfo(menuInfo instance);
    partial void Insertpowers(powers instance);
    partial void Updatepowers(powers instance);
    partial void Deletepowers(powers instance);
    partial void Insertspecialty(specialty instance);
    partial void Updatespecialty(specialty instance);
    partial void Deletespecialty(specialty instance);
    partial void Insertclasses(classes instance);
    partial void Updateclasses(classes instance);
    partial void Deleteclasses(classes instance);
    partial void Insertstudent(student instance);
    partial void Updatestudent(student instance);
    partial void Deletestudent(student instance);
    partial void Insertscore(score instance);
    partial void Updatescore(score instance);
    partial void Deletescore(score instance);
    #endregion
		
		public DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["educationalManagerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<course> course
		{
			get
			{
				return this.GetTable<course>();
			}
		}
		
		public System.Data.Linq.Table<department> department
		{
			get
			{
				return this.GetTable<department>();
			}
		}
		
		public System.Data.Linq.Table<grade> grade
		{
			get
			{
				return this.GetTable<grade>();
			}
		}
		
		public System.Data.Linq.Table<semester> semester
		{
			get
			{
				return this.GetTable<semester>();
			}
		}
		
		public System.Data.Linq.Table<teacher> teacher
		{
			get
			{
				return this.GetTable<teacher>();
			}
		}
		
		public System.Data.Linq.Table<webInfo> webInfo
		{
			get
			{
				return this.GetTable<webInfo>();
			}
		}
		
		public System.Data.Linq.Table<menuInfo> menuInfo
		{
			get
			{
				return this.GetTable<menuInfo>();
			}
		}
		
		public System.Data.Linq.Table<powers> powers
		{
			get
			{
				return this.GetTable<powers>();
			}
		}
		
		public System.Data.Linq.Table<specialty> specialty
		{
			get
			{
				return this.GetTable<specialty>();
			}
		}
		
		public System.Data.Linq.Table<classes> classes
		{
			get
			{
				return this.GetTable<classes>();
			}
		}
		
		public System.Data.Linq.Table<student> student
		{
			get
			{
				return this.GetTable<student>();
			}
		}
		
		public System.Data.Linq.Table<score> score
		{
			get
			{
				return this.GetTable<score>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.course")]
	public partial class course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cs_id;
		
		private string _cs_name;
		
		private System.Nullable<int> _cs_stid;
		
		private string _cs_remark;
		
		private EntitySet<score> _score;
		
		private EntityRef<semester> _semester;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncs_idChanging(int value);
    partial void Oncs_idChanged();
    partial void Oncs_nameChanging(string value);
    partial void Oncs_nameChanged();
    partial void Oncs_stidChanging(System.Nullable<int> value);
    partial void Oncs_stidChanged();
    partial void Oncs_remarkChanging(string value);
    partial void Oncs_remarkChanged();
    #endregion
		
		public course()
		{
			this._score = new EntitySet<score>(new Action<score>(this.attach_score), new Action<score>(this.detach_score));
			this._semester = default(EntityRef<semester>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cs_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cs_id
		{
			get
			{
				return this._cs_id;
			}
			set
			{
				if ((this._cs_id != value))
				{
					this.Oncs_idChanging(value);
					this.SendPropertyChanging();
					this._cs_id = value;
					this.SendPropertyChanged("cs_id");
					this.Oncs_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cs_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string cs_name
		{
			get
			{
				return this._cs_name;
			}
			set
			{
				if ((this._cs_name != value))
				{
					this.Oncs_nameChanging(value);
					this.SendPropertyChanging();
					this._cs_name = value;
					this.SendPropertyChanged("cs_name");
					this.Oncs_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cs_stid", DbType="Int")]
		public System.Nullable<int> cs_stid
		{
			get
			{
				return this._cs_stid;
			}
			set
			{
				if ((this._cs_stid != value))
				{
					if (this._semester.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncs_stidChanging(value);
					this.SendPropertyChanging();
					this._cs_stid = value;
					this.SendPropertyChanged("cs_stid");
					this.Oncs_stidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cs_remark", DbType="NVarChar(1000)")]
		public string cs_remark
		{
			get
			{
				return this._cs_remark;
			}
			set
			{
				if ((this._cs_remark != value))
				{
					this.Oncs_remarkChanging(value);
					this.SendPropertyChanging();
					this._cs_remark = value;
					this.SendPropertyChanged("cs_remark");
					this.Oncs_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_score", Storage="_score", ThisKey="cs_id", OtherKey="sc_csid")]
		public EntitySet<score> score
		{
			get
			{
				return this._score;
			}
			set
			{
				this._score.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="semester_course", Storage="_semester", ThisKey="cs_stid", OtherKey="st_id", IsForeignKey=true)]
		public semester semester
		{
			get
			{
				return this._semester.Entity;
			}
			set
			{
				semester previousValue = this._semester.Entity;
				if (((previousValue != value) 
							|| (this._semester.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._semester.Entity = null;
						previousValue.course.Remove(this);
					}
					this._semester.Entity = value;
					if ((value != null))
					{
						value.course.Add(this);
						this._cs_stid = value.st_id;
					}
					else
					{
						this._cs_stid = default(Nullable<int>);
					}
					this.SendPropertyChanged("semester");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_score(score entity)
		{
			this.SendPropertyChanging();
			entity.course = this;
		}
		
		private void detach_score(score entity)
		{
			this.SendPropertyChanging();
			entity.course = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.department")]
	public partial class department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dp_id;
		
		private string _dp_name;
		
		private string _dp_type;
		
		private System.Nullable<System.DateTime> _dp_cretateTime;
		
		private string _dp_leader;
		
		private string _dp_campus;
		
		private string _dp_remark;
		
		private EntitySet<teacher> _teacher;
		
		private EntitySet<specialty> _specialty;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondp_idChanging(int value);
    partial void Ondp_idChanged();
    partial void Ondp_nameChanging(string value);
    partial void Ondp_nameChanged();
    partial void Ondp_typeChanging(string value);
    partial void Ondp_typeChanged();
    partial void Ondp_cretateTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondp_cretateTimeChanged();
    partial void Ondp_leaderChanging(string value);
    partial void Ondp_leaderChanged();
    partial void Ondp_campusChanging(string value);
    partial void Ondp_campusChanged();
    partial void Ondp_remarkChanging(string value);
    partial void Ondp_remarkChanged();
    #endregion
		
		public department()
		{
			this._teacher = new EntitySet<teacher>(new Action<teacher>(this.attach_teacher), new Action<teacher>(this.detach_teacher));
			this._specialty = new EntitySet<specialty>(new Action<specialty>(this.attach_specialty), new Action<specialty>(this.detach_specialty));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dp_id
		{
			get
			{
				return this._dp_id;
			}
			set
			{
				if ((this._dp_id != value))
				{
					this.Ondp_idChanging(value);
					this.SendPropertyChanging();
					this._dp_id = value;
					this.SendPropertyChanged("dp_id");
					this.Ondp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string dp_name
		{
			get
			{
				return this._dp_name;
			}
			set
			{
				if ((this._dp_name != value))
				{
					this.Ondp_nameChanging(value);
					this.SendPropertyChanging();
					this._dp_name = value;
					this.SendPropertyChanged("dp_name");
					this.Ondp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp_type", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string dp_type
		{
			get
			{
				return this._dp_type;
			}
			set
			{
				if ((this._dp_type != value))
				{
					this.Ondp_typeChanging(value);
					this.SendPropertyChanging();
					this._dp_type = value;
					this.SendPropertyChanged("dp_type");
					this.Ondp_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp_cretateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dp_cretateTime
		{
			get
			{
				return this._dp_cretateTime;
			}
			set
			{
				if ((this._dp_cretateTime != value))
				{
					this.Ondp_cretateTimeChanging(value);
					this.SendPropertyChanging();
					this._dp_cretateTime = value;
					this.SendPropertyChanged("dp_cretateTime");
					this.Ondp_cretateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp_leader", DbType="NVarChar(20)")]
		public string dp_leader
		{
			get
			{
				return this._dp_leader;
			}
			set
			{
				if ((this._dp_leader != value))
				{
					this.Ondp_leaderChanging(value);
					this.SendPropertyChanging();
					this._dp_leader = value;
					this.SendPropertyChanged("dp_leader");
					this.Ondp_leaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp_campus", DbType="NVarChar(200)")]
		public string dp_campus
		{
			get
			{
				return this._dp_campus;
			}
			set
			{
				if ((this._dp_campus != value))
				{
					this.Ondp_campusChanging(value);
					this.SendPropertyChanging();
					this._dp_campus = value;
					this.SendPropertyChanged("dp_campus");
					this.Ondp_campusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp_remark", DbType="NVarChar(1000)")]
		public string dp_remark
		{
			get
			{
				return this._dp_remark;
			}
			set
			{
				if ((this._dp_remark != value))
				{
					this.Ondp_remarkChanging(value);
					this.SendPropertyChanging();
					this._dp_remark = value;
					this.SendPropertyChanged("dp_remark");
					this.Ondp_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="department_teacher", Storage="_teacher", ThisKey="dp_id", OtherKey="th_dpid")]
		public EntitySet<teacher> teacher
		{
			get
			{
				return this._teacher;
			}
			set
			{
				this._teacher.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="department_specialty", Storage="_specialty", ThisKey="dp_id", OtherKey="sp_dpid")]
		public EntitySet<specialty> specialty
		{
			get
			{
				return this._specialty;
			}
			set
			{
				this._specialty.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_teacher(teacher entity)
		{
			this.SendPropertyChanging();
			entity.department = this;
		}
		
		private void detach_teacher(teacher entity)
		{
			this.SendPropertyChanging();
			entity.department = null;
		}
		
		private void attach_specialty(specialty entity)
		{
			this.SendPropertyChanging();
			entity.department = this;
		}
		
		private void detach_specialty(specialty entity)
		{
			this.SendPropertyChanging();
			entity.department = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.grade")]
	public partial class grade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gd_id;
		
		private string _gd_name;
		
		private string _gd_remark;
		
		private EntitySet<specialty> _specialty;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongd_idChanging(int value);
    partial void Ongd_idChanged();
    partial void Ongd_nameChanging(string value);
    partial void Ongd_nameChanged();
    partial void Ongd_remarkChanging(string value);
    partial void Ongd_remarkChanged();
    #endregion
		
		public grade()
		{
			this._specialty = new EntitySet<specialty>(new Action<specialty>(this.attach_specialty), new Action<specialty>(this.detach_specialty));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gd_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int gd_id
		{
			get
			{
				return this._gd_id;
			}
			set
			{
				if ((this._gd_id != value))
				{
					this.Ongd_idChanging(value);
					this.SendPropertyChanging();
					this._gd_id = value;
					this.SendPropertyChanged("gd_id");
					this.Ongd_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gd_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string gd_name
		{
			get
			{
				return this._gd_name;
			}
			set
			{
				if ((this._gd_name != value))
				{
					this.Ongd_nameChanging(value);
					this.SendPropertyChanging();
					this._gd_name = value;
					this.SendPropertyChanged("gd_name");
					this.Ongd_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gd_remark", DbType="NVarChar(1000)")]
		public string gd_remark
		{
			get
			{
				return this._gd_remark;
			}
			set
			{
				if ((this._gd_remark != value))
				{
					this.Ongd_remarkChanging(value);
					this.SendPropertyChanging();
					this._gd_remark = value;
					this.SendPropertyChanged("gd_remark");
					this.Ongd_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grade_specialty", Storage="_specialty", ThisKey="gd_id", OtherKey="sp_gdid")]
		public EntitySet<specialty> specialty
		{
			get
			{
				return this._specialty;
			}
			set
			{
				this._specialty.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_specialty(specialty entity)
		{
			this.SendPropertyChanging();
			entity.grade = this;
		}
		
		private void detach_specialty(specialty entity)
		{
			this.SendPropertyChanging();
			entity.grade = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.semester")]
	public partial class semester : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _st_id;
		
		private string _st_name;
		
		private string _st_remark;
		
		private EntitySet<course> _course;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onst_idChanging(int value);
    partial void Onst_idChanged();
    partial void Onst_nameChanging(string value);
    partial void Onst_nameChanged();
    partial void Onst_remarkChanging(string value);
    partial void Onst_remarkChanged();
    #endregion
		
		public semester()
		{
			this._course = new EntitySet<course>(new Action<course>(this.attach_course), new Action<course>(this.detach_course));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int st_id
		{
			get
			{
				return this._st_id;
			}
			set
			{
				if ((this._st_id != value))
				{
					this.Onst_idChanging(value);
					this.SendPropertyChanging();
					this._st_id = value;
					this.SendPropertyChanged("st_id");
					this.Onst_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string st_name
		{
			get
			{
				return this._st_name;
			}
			set
			{
				if ((this._st_name != value))
				{
					this.Onst_nameChanging(value);
					this.SendPropertyChanging();
					this._st_name = value;
					this.SendPropertyChanged("st_name");
					this.Onst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st_remark", DbType="NVarChar(1000)")]
		public string st_remark
		{
			get
			{
				return this._st_remark;
			}
			set
			{
				if ((this._st_remark != value))
				{
					this.Onst_remarkChanging(value);
					this.SendPropertyChanging();
					this._st_remark = value;
					this.SendPropertyChanged("st_remark");
					this.Onst_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="semester_course", Storage="_course", ThisKey="st_id", OtherKey="cs_stid")]
		public EntitySet<course> course
		{
			get
			{
				return this._course;
			}
			set
			{
				this._course.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_course(course entity)
		{
			this.SendPropertyChanging();
			entity.semester = this;
		}
		
		private void detach_course(course entity)
		{
			this.SendPropertyChanging();
			entity.semester = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.teacher")]
	public partial class teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _th_id;
		
		private string _th_password;
		
		private string _th_name;
		
		private System.Nullable<int> _th_role;
		
		private string _th_sex;
		
		private string _th_education;
		
		private string _th_title;
		
		private string _th_sSpecialty;
		
		private string _th_nation;
		
		private string _th_address;
		
		private string _th_tel;
		
		private string _th_politicalOutlook;
		
		private string _th_cid;
		
		private string _th_school;
		
		private System.Nullable<int> _th_dpid;
		
		private string _th_nowAddress;
		
		private System.Nullable<System.DateTime> _th_birth;
		
		private System.Nullable<System.DateTime> _th_joinTime;
		
		private string _th_classes;
		
		private string _th_remark;
		
		private EntityRef<department> _department;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onth_idChanging(int value);
    partial void Onth_idChanged();
    partial void Onth_passwordChanging(string value);
    partial void Onth_passwordChanged();
    partial void Onth_nameChanging(string value);
    partial void Onth_nameChanged();
    partial void Onth_roleChanging(System.Nullable<int> value);
    partial void Onth_roleChanged();
    partial void Onth_sexChanging(string value);
    partial void Onth_sexChanged();
    partial void Onth_educationChanging(string value);
    partial void Onth_educationChanged();
    partial void Onth_titleChanging(string value);
    partial void Onth_titleChanged();
    partial void Onth_sSpecialtyChanging(string value);
    partial void Onth_sSpecialtyChanged();
    partial void Onth_nationChanging(string value);
    partial void Onth_nationChanged();
    partial void Onth_addressChanging(string value);
    partial void Onth_addressChanged();
    partial void Onth_telChanging(string value);
    partial void Onth_telChanged();
    partial void Onth_politicalOutlookChanging(string value);
    partial void Onth_politicalOutlookChanged();
    partial void Onth_cidChanging(string value);
    partial void Onth_cidChanged();
    partial void Onth_schoolChanging(string value);
    partial void Onth_schoolChanged();
    partial void Onth_dpidChanging(System.Nullable<int> value);
    partial void Onth_dpidChanged();
    partial void Onth_nowAddressChanging(string value);
    partial void Onth_nowAddressChanged();
    partial void Onth_birthChanging(System.Nullable<System.DateTime> value);
    partial void Onth_birthChanged();
    partial void Onth_joinTimeChanging(System.Nullable<System.DateTime> value);
    partial void Onth_joinTimeChanged();
    partial void Onth_classesChanging(string value);
    partial void Onth_classesChanged();
    partial void Onth_remarkChanging(string value);
    partial void Onth_remarkChanged();
    #endregion
		
		public teacher()
		{
			this._department = default(EntityRef<department>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int th_id
		{
			get
			{
				return this._th_id;
			}
			set
			{
				if ((this._th_id != value))
				{
					this.Onth_idChanging(value);
					this.SendPropertyChanging();
					this._th_id = value;
					this.SendPropertyChanged("th_id");
					this.Onth_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string th_password
		{
			get
			{
				return this._th_password;
			}
			set
			{
				if ((this._th_password != value))
				{
					this.Onth_passwordChanging(value);
					this.SendPropertyChanging();
					this._th_password = value;
					this.SendPropertyChanged("th_password");
					this.Onth_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_name", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string th_name
		{
			get
			{
				return this._th_name;
			}
			set
			{
				if ((this._th_name != value))
				{
					this.Onth_nameChanging(value);
					this.SendPropertyChanging();
					this._th_name = value;
					this.SendPropertyChanged("th_name");
					this.Onth_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_role", DbType="Int")]
		public System.Nullable<int> th_role
		{
			get
			{
				return this._th_role;
			}
			set
			{
				if ((this._th_role != value))
				{
					this.Onth_roleChanging(value);
					this.SendPropertyChanging();
					this._th_role = value;
					this.SendPropertyChanged("th_role");
					this.Onth_roleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_sex", DbType="Char(2)")]
		public string th_sex
		{
			get
			{
				return this._th_sex;
			}
			set
			{
				if ((this._th_sex != value))
				{
					this.Onth_sexChanging(value);
					this.SendPropertyChanging();
					this._th_sex = value;
					this.SendPropertyChanged("th_sex");
					this.Onth_sexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_education", DbType="NVarChar(15)")]
		public string th_education
		{
			get
			{
				return this._th_education;
			}
			set
			{
				if ((this._th_education != value))
				{
					this.Onth_educationChanging(value);
					this.SendPropertyChanging();
					this._th_education = value;
					this.SendPropertyChanged("th_education");
					this.Onth_educationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_title", DbType="NVarChar(20)")]
		public string th_title
		{
			get
			{
				return this._th_title;
			}
			set
			{
				if ((this._th_title != value))
				{
					this.Onth_titleChanging(value);
					this.SendPropertyChanging();
					this._th_title = value;
					this.SendPropertyChanged("th_title");
					this.Onth_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_sSpecialty", DbType="NVarChar(20)")]
		public string th_sSpecialty
		{
			get
			{
				return this._th_sSpecialty;
			}
			set
			{
				if ((this._th_sSpecialty != value))
				{
					this.Onth_sSpecialtyChanging(value);
					this.SendPropertyChanging();
					this._th_sSpecialty = value;
					this.SendPropertyChanged("th_sSpecialty");
					this.Onth_sSpecialtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_nation", DbType="NVarChar(20)")]
		public string th_nation
		{
			get
			{
				return this._th_nation;
			}
			set
			{
				if ((this._th_nation != value))
				{
					this.Onth_nationChanging(value);
					this.SendPropertyChanging();
					this._th_nation = value;
					this.SendPropertyChanged("th_nation");
					this.Onth_nationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_address", DbType="NVarChar(100)")]
		public string th_address
		{
			get
			{
				return this._th_address;
			}
			set
			{
				if ((this._th_address != value))
				{
					this.Onth_addressChanging(value);
					this.SendPropertyChanging();
					this._th_address = value;
					this.SendPropertyChanged("th_address");
					this.Onth_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_tel", DbType="NVarChar(30)")]
		public string th_tel
		{
			get
			{
				return this._th_tel;
			}
			set
			{
				if ((this._th_tel != value))
				{
					this.Onth_telChanging(value);
					this.SendPropertyChanging();
					this._th_tel = value;
					this.SendPropertyChanged("th_tel");
					this.Onth_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_politicalOutlook", DbType="NVarChar(10)")]
		public string th_politicalOutlook
		{
			get
			{
				return this._th_politicalOutlook;
			}
			set
			{
				if ((this._th_politicalOutlook != value))
				{
					this.Onth_politicalOutlookChanging(value);
					this.SendPropertyChanging();
					this._th_politicalOutlook = value;
					this.SendPropertyChanged("th_politicalOutlook");
					this.Onth_politicalOutlookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_cid", DbType="NVarChar(30)")]
		public string th_cid
		{
			get
			{
				return this._th_cid;
			}
			set
			{
				if ((this._th_cid != value))
				{
					this.Onth_cidChanging(value);
					this.SendPropertyChanging();
					this._th_cid = value;
					this.SendPropertyChanged("th_cid");
					this.Onth_cidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_school", DbType="NVarChar(50)")]
		public string th_school
		{
			get
			{
				return this._th_school;
			}
			set
			{
				if ((this._th_school != value))
				{
					this.Onth_schoolChanging(value);
					this.SendPropertyChanging();
					this._th_school = value;
					this.SendPropertyChanged("th_school");
					this.Onth_schoolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_dpid", DbType="Int")]
		public System.Nullable<int> th_dpid
		{
			get
			{
				return this._th_dpid;
			}
			set
			{
				if ((this._th_dpid != value))
				{
					if (this._department.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onth_dpidChanging(value);
					this.SendPropertyChanging();
					this._th_dpid = value;
					this.SendPropertyChanged("th_dpid");
					this.Onth_dpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_nowAddress", DbType="NVarChar(200)")]
		public string th_nowAddress
		{
			get
			{
				return this._th_nowAddress;
			}
			set
			{
				if ((this._th_nowAddress != value))
				{
					this.Onth_nowAddressChanging(value);
					this.SendPropertyChanging();
					this._th_nowAddress = value;
					this.SendPropertyChanged("th_nowAddress");
					this.Onth_nowAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_birth", DbType="DateTime")]
		public System.Nullable<System.DateTime> th_birth
		{
			get
			{
				return this._th_birth;
			}
			set
			{
				if ((this._th_birth != value))
				{
					this.Onth_birthChanging(value);
					this.SendPropertyChanging();
					this._th_birth = value;
					this.SendPropertyChanged("th_birth");
					this.Onth_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_joinTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> th_joinTime
		{
			get
			{
				return this._th_joinTime;
			}
			set
			{
				if ((this._th_joinTime != value))
				{
					this.Onth_joinTimeChanging(value);
					this.SendPropertyChanging();
					this._th_joinTime = value;
					this.SendPropertyChanged("th_joinTime");
					this.Onth_joinTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_classes", DbType="NVarChar(100)")]
		public string th_classes
		{
			get
			{
				return this._th_classes;
			}
			set
			{
				if ((this._th_classes != value))
				{
					this.Onth_classesChanging(value);
					this.SendPropertyChanging();
					this._th_classes = value;
					this.SendPropertyChanged("th_classes");
					this.Onth_classesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_th_remark", DbType="NVarChar(1000)")]
		public string th_remark
		{
			get
			{
				return this._th_remark;
			}
			set
			{
				if ((this._th_remark != value))
				{
					this.Onth_remarkChanging(value);
					this.SendPropertyChanging();
					this._th_remark = value;
					this.SendPropertyChanged("th_remark");
					this.Onth_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="department_teacher", Storage="_department", ThisKey="th_dpid", OtherKey="dp_id", IsForeignKey=true)]
		public department department
		{
			get
			{
				return this._department.Entity;
			}
			set
			{
				department previousValue = this._department.Entity;
				if (((previousValue != value) 
							|| (this._department.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._department.Entity = null;
						previousValue.teacher.Remove(this);
					}
					this._department.Entity = value;
					if ((value != null))
					{
						value.teacher.Add(this);
						this._th_dpid = value.dp_id;
					}
					else
					{
						this._th_dpid = default(Nullable<int>);
					}
					this.SendPropertyChanged("department");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.webInfo")]
	public partial class webInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _web_id;
		
		private string _web_copyright;
		
		private string _web_address;
		
		private string _web_postcode;
		
		private string _web_tel;
		
		private string _web_keywords;
		
		private string _web_desc;
		
		private System.Nullable<int> _web_managerUserID;
		
		private System.Nullable<System.DateTime> _web_createTime;
		
		private System.Nullable<System.DateTime> _web_modifyTime;
		
		private string _web_modifyIP;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onweb_idChanging(int value);
    partial void Onweb_idChanged();
    partial void Onweb_copyrightChanging(string value);
    partial void Onweb_copyrightChanged();
    partial void Onweb_addressChanging(string value);
    partial void Onweb_addressChanged();
    partial void Onweb_postcodeChanging(string value);
    partial void Onweb_postcodeChanged();
    partial void Onweb_telChanging(string value);
    partial void Onweb_telChanged();
    partial void Onweb_keywordsChanging(string value);
    partial void Onweb_keywordsChanged();
    partial void Onweb_descChanging(string value);
    partial void Onweb_descChanged();
    partial void Onweb_managerUserIDChanging(System.Nullable<int> value);
    partial void Onweb_managerUserIDChanged();
    partial void Onweb_createTimeChanging(System.Nullable<System.DateTime> value);
    partial void Onweb_createTimeChanged();
    partial void Onweb_modifyTimeChanging(System.Nullable<System.DateTime> value);
    partial void Onweb_modifyTimeChanged();
    partial void Onweb_modifyIPChanging(string value);
    partial void Onweb_modifyIPChanged();
    #endregion
		
		public webInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int web_id
		{
			get
			{
				return this._web_id;
			}
			set
			{
				if ((this._web_id != value))
				{
					this.Onweb_idChanging(value);
					this.SendPropertyChanging();
					this._web_id = value;
					this.SendPropertyChanged("web_id");
					this.Onweb_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_copyright", DbType="VarChar(500)")]
		public string web_copyright
		{
			get
			{
				return this._web_copyright;
			}
			set
			{
				if ((this._web_copyright != value))
				{
					this.Onweb_copyrightChanging(value);
					this.SendPropertyChanging();
					this._web_copyright = value;
					this.SendPropertyChanged("web_copyright");
					this.Onweb_copyrightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_address", DbType="VarChar(500)")]
		public string web_address
		{
			get
			{
				return this._web_address;
			}
			set
			{
				if ((this._web_address != value))
				{
					this.Onweb_addressChanging(value);
					this.SendPropertyChanging();
					this._web_address = value;
					this.SendPropertyChanged("web_address");
					this.Onweb_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_postcode", DbType="VarChar(20)")]
		public string web_postcode
		{
			get
			{
				return this._web_postcode;
			}
			set
			{
				if ((this._web_postcode != value))
				{
					this.Onweb_postcodeChanging(value);
					this.SendPropertyChanging();
					this._web_postcode = value;
					this.SendPropertyChanged("web_postcode");
					this.Onweb_postcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_tel", DbType="VarChar(11)")]
		public string web_tel
		{
			get
			{
				return this._web_tel;
			}
			set
			{
				if ((this._web_tel != value))
				{
					this.Onweb_telChanging(value);
					this.SendPropertyChanging();
					this._web_tel = value;
					this.SendPropertyChanged("web_tel");
					this.Onweb_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_keywords", DbType="VarChar(1000)")]
		public string web_keywords
		{
			get
			{
				return this._web_keywords;
			}
			set
			{
				if ((this._web_keywords != value))
				{
					this.Onweb_keywordsChanging(value);
					this.SendPropertyChanging();
					this._web_keywords = value;
					this.SendPropertyChanged("web_keywords");
					this.Onweb_keywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_desc", DbType="VarChar(150)")]
		public string web_desc
		{
			get
			{
				return this._web_desc;
			}
			set
			{
				if ((this._web_desc != value))
				{
					this.Onweb_descChanging(value);
					this.SendPropertyChanging();
					this._web_desc = value;
					this.SendPropertyChanged("web_desc");
					this.Onweb_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_managerUserID", DbType="Int")]
		public System.Nullable<int> web_managerUserID
		{
			get
			{
				return this._web_managerUserID;
			}
			set
			{
				if ((this._web_managerUserID != value))
				{
					this.Onweb_managerUserIDChanging(value);
					this.SendPropertyChanging();
					this._web_managerUserID = value;
					this.SendPropertyChanged("web_managerUserID");
					this.Onweb_managerUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_createTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> web_createTime
		{
			get
			{
				return this._web_createTime;
			}
			set
			{
				if ((this._web_createTime != value))
				{
					this.Onweb_createTimeChanging(value);
					this.SendPropertyChanging();
					this._web_createTime = value;
					this.SendPropertyChanged("web_createTime");
					this.Onweb_createTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_modifyTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> web_modifyTime
		{
			get
			{
				return this._web_modifyTime;
			}
			set
			{
				if ((this._web_modifyTime != value))
				{
					this.Onweb_modifyTimeChanging(value);
					this.SendPropertyChanging();
					this._web_modifyTime = value;
					this.SendPropertyChanged("web_modifyTime");
					this.Onweb_modifyTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_modifyIP", DbType="VarChar(100)")]
		public string web_modifyIP
		{
			get
			{
				return this._web_modifyIP;
			}
			set
			{
				if ((this._web_modifyIP != value))
				{
					this.Onweb_modifyIPChanging(value);
					this.SendPropertyChanging();
					this._web_modifyIP = value;
					this.SendPropertyChanged("web_modifyIP");
					this.Onweb_modifyIPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.menuInfo")]
	public partial class menuInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mn_id;
		
		private string _mn_name;
		
		private System.Nullable<int> _mn_pId;
		
		private string _mn_url;
		
		private string _mn_remark;
		
		private EntitySet<powers> _powers;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmn_idChanging(int value);
    partial void Onmn_idChanged();
    partial void Onmn_nameChanging(string value);
    partial void Onmn_nameChanged();
    partial void Onmn_pIdChanging(System.Nullable<int> value);
    partial void Onmn_pIdChanged();
    partial void Onmn_urlChanging(string value);
    partial void Onmn_urlChanged();
    partial void Onmn_remarkChanging(string value);
    partial void Onmn_remarkChanged();
    #endregion
		
		public menuInfo()
		{
			this._powers = new EntitySet<powers>(new Action<powers>(this.attach_powers), new Action<powers>(this.detach_powers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mn_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mn_id
		{
			get
			{
				return this._mn_id;
			}
			set
			{
				if ((this._mn_id != value))
				{
					this.Onmn_idChanging(value);
					this.SendPropertyChanging();
					this._mn_id = value;
					this.SendPropertyChanged("mn_id");
					this.Onmn_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mn_name", DbType="VarChar(200)")]
		public string mn_name
		{
			get
			{
				return this._mn_name;
			}
			set
			{
				if ((this._mn_name != value))
				{
					this.Onmn_nameChanging(value);
					this.SendPropertyChanging();
					this._mn_name = value;
					this.SendPropertyChanged("mn_name");
					this.Onmn_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mn_pId", DbType="Int")]
		public System.Nullable<int> mn_pId
		{
			get
			{
				return this._mn_pId;
			}
			set
			{
				if ((this._mn_pId != value))
				{
					this.Onmn_pIdChanging(value);
					this.SendPropertyChanging();
					this._mn_pId = value;
					this.SendPropertyChanged("mn_pId");
					this.Onmn_pIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mn_url", DbType="VarChar(500)")]
		public string mn_url
		{
			get
			{
				return this._mn_url;
			}
			set
			{
				if ((this._mn_url != value))
				{
					this.Onmn_urlChanging(value);
					this.SendPropertyChanging();
					this._mn_url = value;
					this.SendPropertyChanged("mn_url");
					this.Onmn_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mn_remark", DbType="VarChar(1000)")]
		public string mn_remark
		{
			get
			{
				return this._mn_remark;
			}
			set
			{
				if ((this._mn_remark != value))
				{
					this.Onmn_remarkChanging(value);
					this.SendPropertyChanging();
					this._mn_remark = value;
					this.SendPropertyChanged("mn_remark");
					this.Onmn_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="menuInfo_powers", Storage="_powers", ThisKey="mn_id", OtherKey="pr_muId")]
		public EntitySet<powers> powers
		{
			get
			{
				return this._powers;
			}
			set
			{
				this._powers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_powers(powers entity)
		{
			this.SendPropertyChanging();
			entity.menuInfo = this;
		}
		
		private void detach_powers(powers entity)
		{
			this.SendPropertyChanging();
			entity.menuInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.powers")]
	public partial class powers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pr_id;
		
		private System.Nullable<int> _pr_roles;
		
		private System.Nullable<int> _pr_muId;
		
		private string _pr_remark;
		
		private EntityRef<menuInfo> _menuInfo;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpr_idChanging(int value);
    partial void Onpr_idChanged();
    partial void Onpr_rolesChanging(System.Nullable<int> value);
    partial void Onpr_rolesChanged();
    partial void Onpr_muIdChanging(System.Nullable<int> value);
    partial void Onpr_muIdChanged();
    partial void Onpr_remarkChanging(string value);
    partial void Onpr_remarkChanged();
    #endregion
		
		public powers()
		{
			this._menuInfo = default(EntityRef<menuInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pr_id
		{
			get
			{
				return this._pr_id;
			}
			set
			{
				if ((this._pr_id != value))
				{
					this.Onpr_idChanging(value);
					this.SendPropertyChanging();
					this._pr_id = value;
					this.SendPropertyChanged("pr_id");
					this.Onpr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_roles", DbType="Int")]
		public System.Nullable<int> pr_roles
		{
			get
			{
				return this._pr_roles;
			}
			set
			{
				if ((this._pr_roles != value))
				{
					this.Onpr_rolesChanging(value);
					this.SendPropertyChanging();
					this._pr_roles = value;
					this.SendPropertyChanged("pr_roles");
					this.Onpr_rolesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_muId", DbType="Int")]
		public System.Nullable<int> pr_muId
		{
			get
			{
				return this._pr_muId;
			}
			set
			{
				if ((this._pr_muId != value))
				{
					if (this._menuInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpr_muIdChanging(value);
					this.SendPropertyChanging();
					this._pr_muId = value;
					this.SendPropertyChanged("pr_muId");
					this.Onpr_muIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_remark", DbType="VarChar(1000)")]
		public string pr_remark
		{
			get
			{
				return this._pr_remark;
			}
			set
			{
				if ((this._pr_remark != value))
				{
					this.Onpr_remarkChanging(value);
					this.SendPropertyChanging();
					this._pr_remark = value;
					this.SendPropertyChanged("pr_remark");
					this.Onpr_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="menuInfo_powers", Storage="_menuInfo", ThisKey="pr_muId", OtherKey="mn_id", IsForeignKey=true)]
		public menuInfo menuInfo
		{
			get
			{
				return this._menuInfo.Entity;
			}
			set
			{
				menuInfo previousValue = this._menuInfo.Entity;
				if (((previousValue != value) 
							|| (this._menuInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._menuInfo.Entity = null;
						previousValue.powers.Remove(this);
					}
					this._menuInfo.Entity = value;
					if ((value != null))
					{
						value.powers.Add(this);
						this._pr_muId = value.mn_id;
					}
					else
					{
						this._pr_muId = default(Nullable<int>);
					}
					this.SendPropertyChanged("menuInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.specialty")]
	public partial class specialty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sp_id;
		
		private string _sp_name;
		
		private System.Nullable<int> _sp_dpid;
		
		private System.Nullable<int> _sp_gdid;
		
		private string _sp_csids;
		
		private string _sp_remark;
		
		private EntitySet<classes> _classes;
		
		private EntityRef<department> _department;
		
		private EntityRef<grade> _grade;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsp_idChanging(int value);
    partial void Onsp_idChanged();
    partial void Onsp_nameChanging(string value);
    partial void Onsp_nameChanged();
    partial void Onsp_dpidChanging(System.Nullable<int> value);
    partial void Onsp_dpidChanged();
    partial void Onsp_gdidChanging(System.Nullable<int> value);
    partial void Onsp_gdidChanged();
    partial void Onsp_csidsChanging(string value);
    partial void Onsp_csidsChanged();
    partial void Onsp_remarkChanging(string value);
    partial void Onsp_remarkChanged();
    #endregion
		
		public specialty()
		{
			this._classes = new EntitySet<classes>(new Action<classes>(this.attach_classes), new Action<classes>(this.detach_classes));
			this._department = default(EntityRef<department>);
			this._grade = default(EntityRef<grade>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sp_id
		{
			get
			{
				return this._sp_id;
			}
			set
			{
				if ((this._sp_id != value))
				{
					this.Onsp_idChanging(value);
					this.SendPropertyChanging();
					this._sp_id = value;
					this.SendPropertyChanged("sp_id");
					this.Onsp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string sp_name
		{
			get
			{
				return this._sp_name;
			}
			set
			{
				if ((this._sp_name != value))
				{
					this.Onsp_nameChanging(value);
					this.SendPropertyChanging();
					this._sp_name = value;
					this.SendPropertyChanged("sp_name");
					this.Onsp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_dpid", DbType="Int")]
		public System.Nullable<int> sp_dpid
		{
			get
			{
				return this._sp_dpid;
			}
			set
			{
				if ((this._sp_dpid != value))
				{
					if (this._department.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsp_dpidChanging(value);
					this.SendPropertyChanging();
					this._sp_dpid = value;
					this.SendPropertyChanged("sp_dpid");
					this.Onsp_dpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_gdid", DbType="Int")]
		public System.Nullable<int> sp_gdid
		{
			get
			{
				return this._sp_gdid;
			}
			set
			{
				if ((this._sp_gdid != value))
				{
					if (this._grade.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsp_gdidChanging(value);
					this.SendPropertyChanging();
					this._sp_gdid = value;
					this.SendPropertyChanged("sp_gdid");
					this.Onsp_gdidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_csids", DbType="VarChar(200)")]
		public string sp_csids
		{
			get
			{
				return this._sp_csids;
			}
			set
			{
				if ((this._sp_csids != value))
				{
					this.Onsp_csidsChanging(value);
					this.SendPropertyChanging();
					this._sp_csids = value;
					this.SendPropertyChanged("sp_csids");
					this.Onsp_csidsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_remark", DbType="NVarChar(1000)")]
		public string sp_remark
		{
			get
			{
				return this._sp_remark;
			}
			set
			{
				if ((this._sp_remark != value))
				{
					this.Onsp_remarkChanging(value);
					this.SendPropertyChanging();
					this._sp_remark = value;
					this.SendPropertyChanged("sp_remark");
					this.Onsp_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="specialty_classes", Storage="_classes", ThisKey="sp_id", OtherKey="cl_spid")]
		public EntitySet<classes> classes
		{
			get
			{
				return this._classes;
			}
			set
			{
				this._classes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="department_specialty", Storage="_department", ThisKey="sp_dpid", OtherKey="dp_id", IsForeignKey=true)]
		public department department
		{
			get
			{
				return this._department.Entity;
			}
			set
			{
				department previousValue = this._department.Entity;
				if (((previousValue != value) 
							|| (this._department.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._department.Entity = null;
						previousValue.specialty.Remove(this);
					}
					this._department.Entity = value;
					if ((value != null))
					{
						value.specialty.Add(this);
						this._sp_dpid = value.dp_id;
					}
					else
					{
						this._sp_dpid = default(Nullable<int>);
					}
					this.SendPropertyChanged("department");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grade_specialty", Storage="_grade", ThisKey="sp_gdid", OtherKey="gd_id", IsForeignKey=true)]
		public grade grade
		{
			get
			{
				return this._grade.Entity;
			}
			set
			{
				grade previousValue = this._grade.Entity;
				if (((previousValue != value) 
							|| (this._grade.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._grade.Entity = null;
						previousValue.specialty.Remove(this);
					}
					this._grade.Entity = value;
					if ((value != null))
					{
						value.specialty.Add(this);
						this._sp_gdid = value.gd_id;
					}
					else
					{
						this._sp_gdid = default(Nullable<int>);
					}
					this.SendPropertyChanged("grade");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_classes(classes entity)
		{
			this.SendPropertyChanging();
			entity.specialty = this;
		}
		
		private void detach_classes(classes entity)
		{
			this.SendPropertyChanging();
			entity.specialty = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.classes")]
	public partial class classes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cl_id;
		
		private string _cl_name;
		
		private System.Nullable<int> _cl_spid;
		
		private string _cl_room;
		
		private string _cl_remark;
		
		private EntitySet<student> _student;
		
		private EntityRef<specialty> _specialty;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncl_idChanging(int value);
    partial void Oncl_idChanged();
    partial void Oncl_nameChanging(string value);
    partial void Oncl_nameChanged();
    partial void Oncl_spidChanging(System.Nullable<int> value);
    partial void Oncl_spidChanged();
    partial void Oncl_roomChanging(string value);
    partial void Oncl_roomChanged();
    partial void Oncl_remarkChanging(string value);
    partial void Oncl_remarkChanged();
    #endregion
		
		public classes()
		{
			this._student = new EntitySet<student>(new Action<student>(this.attach_student), new Action<student>(this.detach_student));
			this._specialty = default(EntityRef<specialty>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cl_id
		{
			get
			{
				return this._cl_id;
			}
			set
			{
				if ((this._cl_id != value))
				{
					this.Oncl_idChanging(value);
					this.SendPropertyChanging();
					this._cl_id = value;
					this.SendPropertyChanged("cl_id");
					this.Oncl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string cl_name
		{
			get
			{
				return this._cl_name;
			}
			set
			{
				if ((this._cl_name != value))
				{
					this.Oncl_nameChanging(value);
					this.SendPropertyChanging();
					this._cl_name = value;
					this.SendPropertyChanged("cl_name");
					this.Oncl_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_spid", DbType="Int")]
		public System.Nullable<int> cl_spid
		{
			get
			{
				return this._cl_spid;
			}
			set
			{
				if ((this._cl_spid != value))
				{
					if (this._specialty.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncl_spidChanging(value);
					this.SendPropertyChanging();
					this._cl_spid = value;
					this.SendPropertyChanged("cl_spid");
					this.Oncl_spidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_room", DbType="NVarChar(200)")]
		public string cl_room
		{
			get
			{
				return this._cl_room;
			}
			set
			{
				if ((this._cl_room != value))
				{
					this.Oncl_roomChanging(value);
					this.SendPropertyChanging();
					this._cl_room = value;
					this.SendPropertyChanged("cl_room");
					this.Oncl_roomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_remark", DbType="NVarChar(1000)")]
		public string cl_remark
		{
			get
			{
				return this._cl_remark;
			}
			set
			{
				if ((this._cl_remark != value))
				{
					this.Oncl_remarkChanging(value);
					this.SendPropertyChanging();
					this._cl_remark = value;
					this.SendPropertyChanged("cl_remark");
					this.Oncl_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="classes_student", Storage="_student", ThisKey="cl_id", OtherKey="stu_clid")]
		public EntitySet<student> student
		{
			get
			{
				return this._student;
			}
			set
			{
				this._student.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="specialty_classes", Storage="_specialty", ThisKey="cl_spid", OtherKey="sp_id", IsForeignKey=true)]
		public specialty specialty
		{
			get
			{
				return this._specialty.Entity;
			}
			set
			{
				specialty previousValue = this._specialty.Entity;
				if (((previousValue != value) 
							|| (this._specialty.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._specialty.Entity = null;
						previousValue.classes.Remove(this);
					}
					this._specialty.Entity = value;
					if ((value != null))
					{
						value.classes.Add(this);
						this._cl_spid = value.sp_id;
					}
					else
					{
						this._cl_spid = default(Nullable<int>);
					}
					this.SendPropertyChanged("specialty");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_student(student entity)
		{
			this.SendPropertyChanging();
			entity.classes = this;
		}
		
		private void detach_student(student entity)
		{
			this.SendPropertyChanging();
			entity.classes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.student")]
	public partial class student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _stu_num;
		
		private string _stu_password;
		
		private string _stu_name;
		
		private string _stu_sex;
		
		private System.Nullable<System.DateTime> _stu_birth;
		
		private string _stu_nation;
		
		private string _stu_cid;
		
		private string _stu_tel;
		
		private string _stu_address;
		
		private System.Nullable<int> _stu_clid;
		
		private string _stu_politicalOutlook;
		
		private System.Nullable<System.DateTime> _stu_joinTime;
		
		private string _stu_highSchool;
		
		private string _stu_remark;
		
		private EntitySet<score> _score;
		
		private EntityRef<classes> _classes;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstu_numChanging(int value);
    partial void Onstu_numChanged();
    partial void Onstu_passwordChanging(string value);
    partial void Onstu_passwordChanged();
    partial void Onstu_nameChanging(string value);
    partial void Onstu_nameChanged();
    partial void Onstu_sexChanging(string value);
    partial void Onstu_sexChanged();
    partial void Onstu_birthChanging(System.Nullable<System.DateTime> value);
    partial void Onstu_birthChanged();
    partial void Onstu_nationChanging(string value);
    partial void Onstu_nationChanged();
    partial void Onstu_cidChanging(string value);
    partial void Onstu_cidChanged();
    partial void Onstu_telChanging(string value);
    partial void Onstu_telChanged();
    partial void Onstu_addressChanging(string value);
    partial void Onstu_addressChanged();
    partial void Onstu_clidChanging(System.Nullable<int> value);
    partial void Onstu_clidChanged();
    partial void Onstu_politicalOutlookChanging(string value);
    partial void Onstu_politicalOutlookChanged();
    partial void Onstu_joinTimeChanging(System.Nullable<System.DateTime> value);
    partial void Onstu_joinTimeChanged();
    partial void Onstu_highSchoolChanging(string value);
    partial void Onstu_highSchoolChanged();
    partial void Onstu_remarkChanging(string value);
    partial void Onstu_remarkChanged();
    #endregion
		
		public student()
		{
			this._score = new EntitySet<score>(new Action<score>(this.attach_score), new Action<score>(this.detach_score));
			this._classes = default(EntityRef<classes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_num", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int stu_num
		{
			get
			{
				return this._stu_num;
			}
			set
			{
				if ((this._stu_num != value))
				{
					this.Onstu_numChanging(value);
					this.SendPropertyChanging();
					this._stu_num = value;
					this.SendPropertyChanged("stu_num");
					this.Onstu_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_password", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string stu_password
		{
			get
			{
				return this._stu_password;
			}
			set
			{
				if ((this._stu_password != value))
				{
					this.Onstu_passwordChanging(value);
					this.SendPropertyChanging();
					this._stu_password = value;
					this.SendPropertyChanged("stu_password");
					this.Onstu_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string stu_name
		{
			get
			{
				return this._stu_name;
			}
			set
			{
				if ((this._stu_name != value))
				{
					this.Onstu_nameChanging(value);
					this.SendPropertyChanging();
					this._stu_name = value;
					this.SendPropertyChanged("stu_name");
					this.Onstu_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_sex", DbType="Char(2)")]
		public string stu_sex
		{
			get
			{
				return this._stu_sex;
			}
			set
			{
				if ((this._stu_sex != value))
				{
					this.Onstu_sexChanging(value);
					this.SendPropertyChanging();
					this._stu_sex = value;
					this.SendPropertyChanged("stu_sex");
					this.Onstu_sexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_birth", DbType="DateTime")]
		public System.Nullable<System.DateTime> stu_birth
		{
			get
			{
				return this._stu_birth;
			}
			set
			{
				if ((this._stu_birth != value))
				{
					this.Onstu_birthChanging(value);
					this.SendPropertyChanging();
					this._stu_birth = value;
					this.SendPropertyChanged("stu_birth");
					this.Onstu_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_nation", DbType="NVarChar(20)")]
		public string stu_nation
		{
			get
			{
				return this._stu_nation;
			}
			set
			{
				if ((this._stu_nation != value))
				{
					this.Onstu_nationChanging(value);
					this.SendPropertyChanging();
					this._stu_nation = value;
					this.SendPropertyChanged("stu_nation");
					this.Onstu_nationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_cid", DbType="NVarChar(30)")]
		public string stu_cid
		{
			get
			{
				return this._stu_cid;
			}
			set
			{
				if ((this._stu_cid != value))
				{
					this.Onstu_cidChanging(value);
					this.SendPropertyChanging();
					this._stu_cid = value;
					this.SendPropertyChanged("stu_cid");
					this.Onstu_cidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_tel", DbType="NVarChar(30)")]
		public string stu_tel
		{
			get
			{
				return this._stu_tel;
			}
			set
			{
				if ((this._stu_tel != value))
				{
					this.Onstu_telChanging(value);
					this.SendPropertyChanging();
					this._stu_tel = value;
					this.SendPropertyChanged("stu_tel");
					this.Onstu_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_address", DbType="NVarChar(200)")]
		public string stu_address
		{
			get
			{
				return this._stu_address;
			}
			set
			{
				if ((this._stu_address != value))
				{
					this.Onstu_addressChanging(value);
					this.SendPropertyChanging();
					this._stu_address = value;
					this.SendPropertyChanged("stu_address");
					this.Onstu_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_clid", DbType="Int")]
		public System.Nullable<int> stu_clid
		{
			get
			{
				return this._stu_clid;
			}
			set
			{
				if ((this._stu_clid != value))
				{
					if (this._classes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onstu_clidChanging(value);
					this.SendPropertyChanging();
					this._stu_clid = value;
					this.SendPropertyChanged("stu_clid");
					this.Onstu_clidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_politicalOutlook", DbType="NVarChar(10)")]
		public string stu_politicalOutlook
		{
			get
			{
				return this._stu_politicalOutlook;
			}
			set
			{
				if ((this._stu_politicalOutlook != value))
				{
					this.Onstu_politicalOutlookChanging(value);
					this.SendPropertyChanging();
					this._stu_politicalOutlook = value;
					this.SendPropertyChanged("stu_politicalOutlook");
					this.Onstu_politicalOutlookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_joinTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> stu_joinTime
		{
			get
			{
				return this._stu_joinTime;
			}
			set
			{
				if ((this._stu_joinTime != value))
				{
					this.Onstu_joinTimeChanging(value);
					this.SendPropertyChanging();
					this._stu_joinTime = value;
					this.SendPropertyChanged("stu_joinTime");
					this.Onstu_joinTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_highSchool", DbType="NVarChar(200)")]
		public string stu_highSchool
		{
			get
			{
				return this._stu_highSchool;
			}
			set
			{
				if ((this._stu_highSchool != value))
				{
					this.Onstu_highSchoolChanging(value);
					this.SendPropertyChanging();
					this._stu_highSchool = value;
					this.SendPropertyChanged("stu_highSchool");
					this.Onstu_highSchoolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stu_remark", DbType="NVarChar(1000)")]
		public string stu_remark
		{
			get
			{
				return this._stu_remark;
			}
			set
			{
				if ((this._stu_remark != value))
				{
					this.Onstu_remarkChanging(value);
					this.SendPropertyChanging();
					this._stu_remark = value;
					this.SendPropertyChanged("stu_remark");
					this.Onstu_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="student_score", Storage="_score", ThisKey="stu_num", OtherKey="sc_stuNum")]
		public EntitySet<score> score
		{
			get
			{
				return this._score;
			}
			set
			{
				this._score.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="classes_student", Storage="_classes", ThisKey="stu_clid", OtherKey="cl_id", IsForeignKey=true)]
		public classes classes
		{
			get
			{
				return this._classes.Entity;
			}
			set
			{
				classes previousValue = this._classes.Entity;
				if (((previousValue != value) 
							|| (this._classes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._classes.Entity = null;
						previousValue.student.Remove(this);
					}
					this._classes.Entity = value;
					if ((value != null))
					{
						value.student.Add(this);
						this._stu_clid = value.cl_id;
					}
					else
					{
						this._stu_clid = default(Nullable<int>);
					}
					this.SendPropertyChanged("classes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_score(score entity)
		{
			this.SendPropertyChanging();
			entity.student = this;
		}
		
		private void detach_score(score entity)
		{
			this.SendPropertyChanging();
			entity.student = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.score")]
	public partial class score : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sc_id;
		
		private System.Nullable<int> _sc_stuNum;
		
		private System.Nullable<int> _sc_csid;
		
		private System.Nullable<int> _sc_usuallyScore;
		
		private System.Nullable<int> _sc_endScore;
		
		private System.Nullable<int> _sc_poportion;
		
		private System.Nullable<int> _sc_sumScore;
		
		private string _sc_remark;
		
		private EntityRef<course> _course;
		
		private EntityRef<student> _student;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsc_idChanging(int value);
    partial void Onsc_idChanged();
    partial void Onsc_stuNumChanging(System.Nullable<int> value);
    partial void Onsc_stuNumChanged();
    partial void Onsc_csidChanging(System.Nullable<int> value);
    partial void Onsc_csidChanged();
    partial void Onsc_usuallyScoreChanging(System.Nullable<int> value);
    partial void Onsc_usuallyScoreChanged();
    partial void Onsc_endScoreChanging(System.Nullable<int> value);
    partial void Onsc_endScoreChanged();
    partial void Onsc_poportionChanging(System.Nullable<int> value);
    partial void Onsc_poportionChanged();
    partial void Onsc_sumScoreChanging(System.Nullable<int> value);
    partial void Onsc_sumScoreChanged();
    partial void Onsc_remarkChanging(string value);
    partial void Onsc_remarkChanged();
    #endregion
		
		public score()
		{
			this._course = default(EntityRef<course>);
			this._student = default(EntityRef<student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sc_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sc_id
		{
			get
			{
				return this._sc_id;
			}
			set
			{
				if ((this._sc_id != value))
				{
					this.Onsc_idChanging(value);
					this.SendPropertyChanging();
					this._sc_id = value;
					this.SendPropertyChanged("sc_id");
					this.Onsc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sc_stuNum", DbType="Int")]
		public System.Nullable<int> sc_stuNum
		{
			get
			{
				return this._sc_stuNum;
			}
			set
			{
				if ((this._sc_stuNum != value))
				{
					if (this._student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsc_stuNumChanging(value);
					this.SendPropertyChanging();
					this._sc_stuNum = value;
					this.SendPropertyChanged("sc_stuNum");
					this.Onsc_stuNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sc_csid", DbType="Int")]
		public System.Nullable<int> sc_csid
		{
			get
			{
				return this._sc_csid;
			}
			set
			{
				if ((this._sc_csid != value))
				{
					if (this._course.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsc_csidChanging(value);
					this.SendPropertyChanging();
					this._sc_csid = value;
					this.SendPropertyChanged("sc_csid");
					this.Onsc_csidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sc_usuallyScore", DbType="Int")]
		public System.Nullable<int> sc_usuallyScore
		{
			get
			{
				return this._sc_usuallyScore;
			}
			set
			{
				if ((this._sc_usuallyScore != value))
				{
					this.Onsc_usuallyScoreChanging(value);
					this.SendPropertyChanging();
					this._sc_usuallyScore = value;
					this.SendPropertyChanged("sc_usuallyScore");
					this.Onsc_usuallyScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sc_endScore", DbType="Int")]
		public System.Nullable<int> sc_endScore
		{
			get
			{
				return this._sc_endScore;
			}
			set
			{
				if ((this._sc_endScore != value))
				{
					this.Onsc_endScoreChanging(value);
					this.SendPropertyChanging();
					this._sc_endScore = value;
					this.SendPropertyChanged("sc_endScore");
					this.Onsc_endScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sc_poportion", DbType="Int")]
		public System.Nullable<int> sc_poportion
		{
			get
			{
				return this._sc_poportion;
			}
			set
			{
				if ((this._sc_poportion != value))
				{
					this.Onsc_poportionChanging(value);
					this.SendPropertyChanging();
					this._sc_poportion = value;
					this.SendPropertyChanged("sc_poportion");
					this.Onsc_poportionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sc_sumScore", DbType="Int")]
		public System.Nullable<int> sc_sumScore
		{
			get
			{
				return this._sc_sumScore;
			}
			set
			{
				if ((this._sc_sumScore != value))
				{
					this.Onsc_sumScoreChanging(value);
					this.SendPropertyChanging();
					this._sc_sumScore = value;
					this.SendPropertyChanged("sc_sumScore");
					this.Onsc_sumScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sc_remark", DbType="NVarChar(1000)")]
		public string sc_remark
		{
			get
			{
				return this._sc_remark;
			}
			set
			{
				if ((this._sc_remark != value))
				{
					this.Onsc_remarkChanging(value);
					this.SendPropertyChanging();
					this._sc_remark = value;
					this.SendPropertyChanged("sc_remark");
					this.Onsc_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_score", Storage="_course", ThisKey="sc_csid", OtherKey="cs_id", IsForeignKey=true)]
		public course course
		{
			get
			{
				return this._course.Entity;
			}
			set
			{
				course previousValue = this._course.Entity;
				if (((previousValue != value) 
							|| (this._course.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._course.Entity = null;
						previousValue.score.Remove(this);
					}
					this._course.Entity = value;
					if ((value != null))
					{
						value.score.Add(this);
						this._sc_csid = value.cs_id;
					}
					else
					{
						this._sc_csid = default(Nullable<int>);
					}
					this.SendPropertyChanged("course");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="student_score", Storage="_student", ThisKey="sc_stuNum", OtherKey="stu_num", IsForeignKey=true)]
		public student student
		{
			get
			{
				return this._student.Entity;
			}
			set
			{
				student previousValue = this._student.Entity;
				if (((previousValue != value) 
							|| (this._student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._student.Entity = null;
						previousValue.score.Remove(this);
					}
					this._student.Entity = value;
					if ((value != null))
					{
						value.score.Add(this);
						this._sc_stuNum = value.stu_num;
					}
					else
					{
						this._sc_stuNum = default(Nullable<int>);
					}
					this.SendPropertyChanged("student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
